; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "OPolyglot"
#define MyAppVersion "0.1.2"
#define MyAppPublisher "Oleksandr Fenenko <fenenko@gmail.com>"
#define MyAppURL "https://opolyglot.sourceforge.io"
#define MyAppExeName "opolyglot.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{BBA8EE47-8FC4-4987-9257-5F870E0C282B}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
AppMutex=OPolyglot
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
LicenseFile=E:\doc\LICENSES.mingw64.txt
; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=lowest
OutputDir=Z:\home\ofenenko\Projects\OPolyglot
OutputBaseFilename=opsetup
Compression=lzma2
SolidCompression=yes
WizardStyle=classic dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "bulgarian"; MessagesFile: "compiler:Languages\Bulgarian.isl"
Name: "czech"; MessagesFile: "compiler:Languages\Czech.isl"
Name: "danish"; MessagesFile: "compiler:Languages\Danish.isl"
Name: "dutch"; MessagesFile: "compiler:Languages\Dutch.isl"
Name: "finnish"; MessagesFile: "compiler:Languages\Finnish.isl"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"
Name: "hungarian"; MessagesFile: "compiler:Languages\Hungarian.isl"
Name: "italian"; MessagesFile: "compiler:Languages\Italian.isl"
Name: "polish"; MessagesFile: "compiler:Languages\Polish.isl"
Name: "portuguese"; MessagesFile: "compiler:Languages\Portuguese.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"
Name: "slovak"; MessagesFile: "compiler:Languages\Slovak.isl"
Name: "slovenian"; MessagesFile: "compiler:Languages\Slovenian.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"
Name: "swedish"; MessagesFile: "compiler:Languages\Swedish.isl"
Name: "turkish"; MessagesFile: "compiler:Languages\Turkish.isl"
Name: "ukrainian"; MessagesFile: "compiler:Languages\Ukrainian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

; E:\ in directory to source code OPolyglot
[Files]
Source: "E:\bin\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\bin\libbergamot-translator-source.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\bin\libgcc_s_seh-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\bin\libgomp-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\bin\libleptonica-1.87.0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\bin\libmarian.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\bin\libopenblas.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\bin\libpcre2-8-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\bin\libstdc++-6.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\bin\libtesseract-5.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\bin\libwinpthread-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\bin\wxbase32u_gcc_custom.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\bin\wxmsw32u_stc_gcc_custom.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\bin\wxmsw32u_core_gcc_custom.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\bin\wxbase32u_xml_gcc_custom.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\bin\libz.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\bin\libcurl.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\bin\libssl-3-x64.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\bin\libcrypto-3-x64.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\bin\cacert.pem"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\bin\res\*"; DestDir: "{app}\res"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "E:\bin\locale\*"; DestDir: "{app}\locale"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "E:\doc\LICENSES.mingw64.txt"; DestDir: "{app}\"; DestName: "LICENSES.txt"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Registry]
Root: HKCU; Subkey: "Software\OPolyglot"; Flags: uninsdeletekey dontcreatekey

[UninstallDelete]
Type: filesandordirs; Name: "{localappdata}\opolyglot"

