; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "OPolyglot"
#define MyAppVersion "Proxima Centauri 1"
#define MyAppPublisher "Oleksandr Fenenko <fenenko@gmail.com>"
#define MyAppURL "https://opolyglot.sourceforge.io"
#define MyAppExeName "opolyglot.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{BBA8EE47-8FC4-4987-9257-5F870E0C282B}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
LicenseFile=Z:\home\ofenenko\Projects\OPolyglot\doc\LICENSES.mingw64.txt
; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=lowest
OutputDir=Z:\home\ofenenko\Projects\OPolyglot
OutputBaseFilename=OPolyglot_setup
Compression=lzma2
SolidCompression=yes
WizardStyle=classic dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "bulgarian"; MessagesFile: "compiler:Languages\Bulgarian.isl"
Name: "czech"; MessagesFile: "compiler:Languages\Czech.isl"
Name: "danish"; MessagesFile: "compiler:Languages\Danish.isl"
Name: "dutch"; MessagesFile: "compiler:Languages\Dutch.isl"
Name: "finnish"; MessagesFile: "compiler:Languages\Finnish.isl"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"
Name: "hungarian"; MessagesFile: "compiler:Languages\Hungarian.isl"
Name: "italian"; MessagesFile: "compiler:Languages\Italian.isl"
Name: "polish"; MessagesFile: "compiler:Languages\Polish.isl"
Name: "portuguese"; MessagesFile: "compiler:Languages\Portuguese.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"
Name: "slovak"; MessagesFile: "compiler:Languages\Slovak.isl"
Name: "slovenian"; MessagesFile: "compiler:Languages\Slovenian.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"
Name: "swedish"; MessagesFile: "compiler:Languages\Swedish.isl"
Name: "turkish"; MessagesFile: "compiler:Languages\Turkish.isl"
Name: "ukrainian"; MessagesFile: "compiler:Languages\Ukrainian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "Z:\home\ofenenko\Projects\OPolyglot\bin\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "Z:\home\ofenenko\Projects\OPolyglot\bin\libbergamot-translator-source.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "Z:\home\ofenenko\Projects\OPolyglot\bin\libgcc_s_seh-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "Z:\home\ofenenko\Projects\OPolyglot\bin\libgomp-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "Z:\home\ofenenko\Projects\OPolyglot\bin\libleptonica-1.88.0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "Z:\home\ofenenko\Projects\OPolyglot\bin\libmarian.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "Z:\home\ofenenko\Projects\OPolyglot\bin\libopenblas.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "Z:\home\ofenenko\Projects\OPolyglot\bin\libopolyglot-ocr-translator.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "Z:\home\ofenenko\Projects\OPolyglot\bin\libpcre2-8-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "Z:\home\ofenenko\Projects\OPolyglot\bin\libstdc++-6.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "Z:\home\ofenenko\Projects\OPolyglot\bin\libtesseract-5.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "Z:\home\ofenenko\Projects\OPolyglot\bin\libtomcrypt.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "Z:\home\ofenenko\Projects\OPolyglot\bin\libtommath.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "Z:\home\ofenenko\Projects\OPolyglot\bin\libwinpthread-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "Z:\home\ofenenko\Projects\OPolyglot\bin\wxmsw32u_gcc_custom.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "Z:\home\ofenenko\Projects\OPolyglot\bin\zlib1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "Z:\home\ofenenko\Projects\OPolyglot\bin\res\*"; DestDir: "{app}\res"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "Z:\home\ofenenko\Projects\OPolyglot\bin\locale\*"; DestDir: "{app}\locale"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "Z:\home\ofenenko\Projects\OPolyglot\doc\LICENSES.mingw64.txt"; DestDir: "{app}\"; DestName: "LICENSES.txt"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

