#pragma once

#define TIMEOUT_CLIPBOARD_CHECKING							200	/* in millisecond */
#define TIMEOUT_CHECK_MOUSE_STATE							200 /* in millisecond */
#define TIMEOUT_FULLSCREAN_CHECK_MOUSE_STATE				200 /* in millisecond */
#define TIME_PRESSED_LEFT									2	/* in count */
#define OPOLYGLOT_LIBRARY									wxS("libopolyglot-ocr-translator.so")
#define OPOLYGLOT_CONFIG_ARGUMENT							wxT("OPolyglot"),wxT("Oleksandr Fenenko"),wxT(".OPolyglot/config")
#define OPOLYGLOT_CONFIG_BOOL_STAY_ON_TOP					wxT("StayOnTop")
#define OPOLYGLOT_CONFIG_BOOL_STAY_ON_TOP_DEFAULT			true
#define OPOLYGLOT_CONFIG_BOOL_METHOD_CREATION_TEXT_NEW		wxS("MethodCreationTextNew") /* true - new , false - append */
#define OPOLYGLOT_CONFIG_BOOL_METHOD_CREATION_TEXT_DEFAULT  true
#define OPOLYGLOT_CONFIG_STRING_LOG_LEVEL					wxT("LogLevel")
#define OPOLYGLOT_CONFIG_STRING_LOG_LEVEL_DEFAULT			wxT("DEBUG")
#define OPOLYGLOT_CONFIG_STRING_LANGUAGE_FROM				wxT("LanguageFrom")
#define OPOLYGLOT_CONFIG_STRING_LANGUAGE_DEFAULT			wxT("English")
#define OPOLYGLOT_CONFIG_STRING_LANGUAGE_TO					wxT("LanguageTo")
#define OPOLYGLOT_CONFIG_STRING_TRANSLATION_METHOD			wxT("TranslationMethod")
#define OPOLYGLOT_CONFIG_STRING_TRANSLATION_METHOD_DEFAULT	wxT("BEST")
#define OPOLYGLOT_CONFIG_STRING_OCR_METHOD					wxT("OCRMethod")
#define OPOLYGLOT_CONFIG_STRING_OCR_METHOD_DEFAULT			wxT("BEST")
#define OPOLYGLOT_CONFIG_BOOL_ENABLED_PREPROCESSING			wxS("EnablePreprocessing")
#define OPOLYGLOT_CONFIG_BOOL_ENABLED_PREPROCESSING_DEFAULT	true
#define OPOLYGLOT_CONFIG_BOOL_ENABLED_POSTPROCESSING			wxS("EnablePostprocessing")
#define OPOLYGLOT_CONFIG_BOOL_ENABLED_POSTPROCESSING_DEFAULT	true



