#pragma once
#include <wx/event.h>

wxDECLARE_EVENT(wxEVT_COMMAND_OPOLYGLOT_SEND_IMAGE,	wxThreadEvent);
wxDECLARE_EVENT(wxEVT_COMMAND_OPOLYGLOT_EXIT,	wxThreadEvent);
wxDECLARE_EVENT(wxEVT_COMMAND_OPOLYGLOT_EXIT_THREAD,	wxThreadEvent);
wxDECLARE_EVENT(wxEVT_COMMAND_OPOLYGLOT_SETUP,					wxThreadEvent);
wxDECLARE_EVENT(wxEVT_COMMAND_OPOLYGLOT_ABOUT,					wxThreadEvent);
wxDECLARE_EVENT(wxEVT_COMMAND_OPOLYGLOT_CHANGE_SHOW,			wxThreadEvent);
wxDECLARE_EVENT(wxEVT_COMMAND_OPOLYGLOT_CANCEL_USER,			wxThreadEvent);
