name: Build dependency and AppImage from Ubuntu 20.04

on:
  push:
    paths:
      - '.github/workflows/build-depends-20.yml'
      - 'scripts/simple-build-dependencies.sh'
      - 'patch/translations.patch'
      - 'Makefile'
      - 'src/*'
  pull_request:
    paths:
      - '.github/workflows/build-depends-20.yml'
      - 'scripts/simple-build-dependencies.sh'
      - 'patch/translations.patch'
      - 'Makefile'
      - 'src/*'
  workflow_dispatch: 

jobs:
  build-and-package:
    runs-on: ubuntu-24.04
    container:
      image: ubuntu:20.04
    
    steps:
      - name: Checkout repository
        if: success()
        uses: actions/checkout@v4

      - name: Install dependencies
        if: success()
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y apt-transport-https ca-certificates gnupg software-properties-common wget
          wget -nv -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
          apt-add-repository 'deb https://apt.kitware.com/ubuntu/ focal main'
          DEBIAN_FRONTEND=noninteractive add-apt-repository ppa:ubuntu-toolchain-r/test -y
          DEBIAN_FRONTEND=noninteractive apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y gcc-13 g++-13 \
          build-essential git wget file pkg-config fuse libfuse2 libsecret-1-dev \
          libtool autoconf automake make perl lzip libglib2.0-dev  \
          meson ninja-build libnotify-dev gettext \
          libopenjp2-7-dev libgtk-3-dev libpng-dev zlib1g-dev libtiff-dev libjpeg-dev libgif-dev libwebp-dev libopenblas-dev libopenblas-serial-dev libopenblas0 libopenblas0-serial libglib2.0-dev

          wget -nv https://github.com/Kitware/CMake/releases/download/v3.17.4/cmake-3.17.4-Linux-x86_64.tar.gz
          tar -xf cmake-3.17.4-Linux-x86_64.tar.gz --strip-components=1 -C /usr/local

          update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100
          update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100 
      
      - name: Build Dependencies
        if: success()
        run: |
          echo "------------------------------------"
          echo "------------------------------------"
          echo "------------------------------------"
          g++ --version
          cmake --version
          meson --version
          cd scripts/
          ./simple-build-dependencies.sh

      - name: Build AppImage
        run: |
          echo "----------------------"
          echo "----------------------"
          echo "----------------------"
          echo "${GITHUB_WORKSPACE}"
          export PKG_CONFIG_PATH="${GITHUB_WORKSPACE}/build/linux/lib/pkgconfig:$PKG_CONFIG_PATH"
          export LD_LIBRARY_PATH="${GITHUB_WORKSPACE}/build/linux/lib:$LD_LIBRARY_PATH"
          make APPIMAGE=1 build
          make compile-po
          wget https://github.com/linuxdeploy/linuxdeploy-plugin-gtk/raw/refs/heads/master/linuxdeploy-plugin-gtk.sh
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy-plugin-gtk.sh
          mkdir -p AppDir/res
          cp bin/cacert.pem AppDir
          cp bin/res/download.xml AppDir/res
          cp bin/LICENSES.txt AppDir
          cp -r bin/locale AppDir
          export APPIMAGE_EXTRACT_AND_RUN=1
          ./linuxdeploy-x86_64.AppImage \
            --appdir AppDir \
            -e ${GITHUB_WORKSPACE}/bin/opolyglot \
            -d ${GITHUB_WORKSPACE}/appimage/opolyglot.desktop \
            -i ${GITHUB_WORKSPACE}/appimage/opolyglot.png \
            --plugin gtk \
            --output appimage
          ls


      - name: Prepare artifact structure
        run: |
          mkdir -p artifact_stage/build
          cp -r build/linux artifact_stage/build
          mkdir -p artifact_stage2/
          cp OPolyglot-x86_64.AppImage artifact_stage2

      - name: Generate timestamp
        id: timestamp
        run: |
          echo "TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dependencies-ubuntu-${{ hashFiles('scripts/simple-build-dependencies.sh', 'patch/translations.patch' , '.github/workflows/build-depends-18.yml') }}
          path: |
            artifact_stage
          if-no-files-found: error


      - name: Upload build artifacts 2
        uses: actions/upload-artifact@v4
        with:
          name: app-image-${{ env.TIMESTAMP }}
          path: |
            artifact_stage2
          if-no-files-found: error


