name: Build Snap Package

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
  pull_request:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Snap
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Build Snap
        id: snapcraft
        uses: snapcore/action-build@v1

      - name: Upload Snap artifact
        uses: actions/upload-artifact@v6
        with:
          name: compiled-snap
          path: ${{ steps.snapcraft.outputs.snap }}
