name: Build AppImage on Ubuntu 20.04

on:
  push:
    paths:
      - '.github/workflows/build-appimage.yml'
      - 'scripts/simple-build-dependencies.sh'
      - 'patch/translations.patch'
      - 'Makefile'
      - 'src/*'
  pull_request:
    paths:
      - '.github/workflows/build-appimage.yml'
      - 'scripts/simple-build-dependencies.sh'
      - 'patch/translations.patch'
      - 'Makefile'
      - 'src/*'
  workflow_dispatch: 
    inputs:
      debug_build:
        description: 'Зібрати з символами відлагодження (NO_STRIP)'
        required: false
        type: boolean
        default: false

jobs:
  build-and-package:
    runs-on: ubuntu-24.04
    container:
      image: ubuntu:20.04
    
    steps:

      - name: Install Git for checkout
        if: success()
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y git

      - name: Checkout repository
        if: success()
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mark repository as safe
        if: success()
        run: |
          git config --global --add safe.directory /__w/OPolyglot/OPolyglot

      - name: Install dependencies
        if: success()
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y apt-transport-https ca-certificates gnupg software-properties-common wget
          wget -nv -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
          apt-add-repository 'deb https://apt.kitware.com/ubuntu/ focal main'
          DEBIAN_FRONTEND=noninteractive add-apt-repository ppa:ubuntu-toolchain-r/test -y
          DEBIAN_FRONTEND=noninteractive apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y gcc-13 g++-13 \
          build-essential bash git wget file pkg-config fuse libfuse2 libsecret-1-dev \
          libtool autoconf automake make perl lzip libglib2.0-dev  \
          meson ninja-build libnotify-dev gettext \
          libopenjp2-7-dev libgtk-3-dev libpng-dev zlib1g-dev libtiff-dev libjpeg-dev libgif-dev libwebp-dev libopenblas-dev libopenblas-serial-dev libopenblas0 libopenblas0-serial libglib2.0-dev

          wget -nv https://github.com/Kitware/CMake/releases/download/v3.17.4/cmake-3.17.4-Linux-x86_64.tar.gz
          tar -xf cmake-3.17.4-Linux-x86_64.tar.gz --strip-components=1 -C /usr/local

          update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100
          update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100 
      
      - name: Build Dependencies
        if: success()
        run: |
          echo "------------------------------------"
          echo "------------------------------------"
          echo "------------------------------------"
          g++ --version
          cmake --version
          meson --version
          cd scripts/
          ./simple-build-dependencies.sh

      - name: Build AppImage
        if: success()
        run: |
          echo "----------------------"
          echo "----------------------"
          echo "----------------------"
          git describe --tags --always --dirty
          mkdir -p ${GITHUB_WORKSPACE}/build/linux/lib/pkgconfig
          export PKG_CONFIG_PATH="${GITHUB_WORKSPACE}/build/linux/lib/pkgconfig:$PKG_CONFIG_PATH"
          export LD_LIBRARY_PATH="${GITHUB_WORKSPACE}/build/linux/lib:$LD_LIBRARY_PATH"
          if [ "${{ inputs.debug_build }}" = "true" ]; then
          echo "-------DEBUGING SYMBOL-------"
          export NO_STRIP=0
          make APPIMAGE=1 build
          else
          make APPIMAGE=1 build
          fi
          export APPIMAGE_EXTRACT_AND_RUN=1
          ./linuxdeploy-x86_64.AppImage \
          --appdir AppDir \
            -e ${GITHUB_WORKSPACE}/bin/opolyglot \
            -d ${GITHUB_WORKSPACE}/AppDir/usr/share/applications/opolyglot.desktop \
            -i ${GITHUB_WORKSPACE}/appimage/opolyglot.png \
            --plugin gtk \
            --output appimage
          rm -rf AppDir 
          ls


      - name: Prepare artifact structure
        if: success()
        run: |
          mkdir -p artifact_stage/build
          cp -r build/linux artifact_stage/build
          mkdir -p artifact_stage2/
          cp OPolyglot-x86_64.AppImage artifact_stage2

      - name: Generate timestamp
        if: success()
        id: timestamp
        run: |
          echo "TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: dependencies-ubuntu-${{ hashFiles('scripts/simple-build-dependencies.sh', 'patch/translations.patch' , '.github/workflows/build-depends-18.yml') }}
          path: |
            artifact_stage
          if-no-files-found: error


      - name: Upload build artifacts 2
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-image-${{ env.TIMESTAMP }}
          path: |
            artifact_stage2
          if-no-files-found: error


