name: Build MinGW Dependencies

on:
  workflow_dispatch: # Дозволяє запускати workflow вручну з інтерфейсу GitHub
  push:
    paths:
      - 'scripts/simple-build-library-win.sh'
      - 'scripts/mingw-toolchain.cmake'
      - 'patch/**'
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  build-and-pack:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Check disk space
        run: |
          df -h
          date

      - name: Install build dependencies, Wine (for libtool path conversion)
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get -o Acquire::ForceIPv4=true update
          sudo apt-get -o Acquire::ForceIPv4=true install -y gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 \
                                    autoconf automake libtool pkg-config cmake make wine lzip

      - name: Cache MinGW dependencies
        id: cache-mingw
        uses: actions/cache@v4
        with:
          path: |
            build/mingw64
            build/src
          # Кеш буде оновлюватися, якщо зміниться скрипт збірки, toolchain або патчі
          key: ${{ runner.os }}-mingw-deps-${{ hashFiles('scripts/simple-build-library-win.sh', 'scripts/mingw-toolchain.cmake', 'patch/*') }}

      - name: Run build script
        if: steps.cache-mingw.outputs.cache-hit != 'true' || github.event_name == 'workflow_dispatch'
        run: |
          chmod +x scripts/simple-build-library-win.sh
          cd scripts
          ./simple-build-library-win.sh

      - name: Generate timestamp
        id: timestamp
        run: |
          # Формат: РРРР-ММ-ДД_ГГ-ХХ-СС
          echo "TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mingw64-deps-${{ env.TIMESTAMP }}
          path: |
            build/mingw64/
          retention-days: 14 # Скільки днів зберігати архів на GitHub
