name: Build OPolyglot Flatpak package

on:
  workflow_dispatch:
    inputs:
      debug_build:
        description: 'Enable OPOLYGLOT_DEBUG_ENABLED 1'
        required: false
        type: boolean
        default: false

  push:
    tags:
      - 'v*'
  pull_request:
    tags:
      - 'v*'

jobs:
  build-flatpak:
    name: Build and Export Flatpak
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install Flatpak dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder elfutils
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          sudo flatpak install -y flathub org.freedesktop.Platform//25.08 
          sudo flatpak install -y flathub org.freedesktop.Sdk//25.08 
          sudo flatpak install -y flathub org.flatpak.Builder
          git config --global protocol.file.allow always

      - name: Build Flatpak via Makefile
        run: |
          if [ "${{ inputs.debug_build }}" = "true" ]; then
            echo "--------DEBUGING BUILD-------------"
            sed -i 's/#define OPOLYGLOT_DEBUG_ENABLED 0/#define OPOLYGLOT_DEBUG_ENABLED 1/' src/Config.h
          else
            echo "--------REGULAR BUILD--------------"
            sed -i 's/#define OPOLYGLOT_DEBUG_ENABLED 1/#define OPOLYGLOT_DEBUG_ENABLED 0/' src/Config.h
          fi
          ls ./
          flatpak info org.freedesktop.Sdk//25.08
          make flatpak
          echo "---------------------"
          echo "---------------------"
          echo "---------------------"
          ls ./

#- name: Build Flatpak
#       uses: flatpak/flatpak-github-actions/flatpak-builder@v6
#       with:
#         bundle: OPolyglot.flatpak
#          manifest-path: flatpak/io.sourceforge.opolyglot.yaml
#          cache-key: flatpak-builder-${{ github.sha }}
      
      - name: Upload Flatpak artifact
        uses: actions/upload-artifact@v6
        with:
          name: opolyglot-flatpaks
          path: |
            opolyglot-x86_64-debug.flatpak
            opolyglot-x86_64.flatpak




