name: Build AppImage (Ubuntu 18.04)

on:
  push:
    paths:
      - '.github/workflows/build-app-image.yml'
      - 'scripts/simple-build-translator.sh'
      - 'patch/translations.patch'
  pull_request:
    paths:
      - '.github/workflows/build-app-image.yml'
      - 'scripts/simple-build-translator.sh'
      - 'patch/translations.patch'
  workflow_dispatch: 

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install Container Build Dependencies
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            ubuntu:18.04 \
            /bin/bash -c "
              # Оновлюємо та ставимо пакети
              cd /
              cd /workspace
              echo \"------------------------------------\"
              echo \"------------------------------------\"
              echo \"------------------------------------\"
              apt-get update
              DEBIAN_FRONTEND=noninteractive apt-get install -y apt-transport-https ca-certificates gnupg software-properties-common wget
              wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
              apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'
              DEBIAN_FRONTEND=noninteractive add-apt-repository ppa:ubuntu-toolchain-r/test -y
              DEBIAN_FRONTEND=noninteractive apt-get update
              DEBIAN_FRONTEND=noninteractive apt-get install -y gcc-13 g++-13 \
                build-essential git wget file pkg-config libfuse2 libsecret-1-dev \
                libtool autoconf automake make meson perl lzip \
                python3 python3-pip python3-setuptools ninja-build libnotify-dev \
                libpng-dev zlib1g-dev libopenjp2-7-dev libtiff-dev libopenblas-dev libgtk-3-dev 
              wget -nv https://github.com/Kitware/CMake/releases/download/v3.17.4/cmake-3.17.4-Linux-x86_64.tar.gz
              tar -xf cmake-3.17.4-Linux-x86_64.tar.gz --strip-components=1 -C /usr/local
              pip3 install meson
              
              # ТУТ ДОДАЙТЕ ВАШІ ЗАЛЕЖНОСТІ (якщо потрібні):
              # apt-get instal
              update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100
              update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100 
              g++ --version
              cmake --version
              git clone https://gitlab.gnome.org/GNOME/glib
              cd glib
              git checkout 2.72.4
              mkdir -p /workspace/build/linux
              meson setup builddir --prefix=/workspace/build/linux --libdir=lib
              ninja -C builddir
              ninja -C builddir install
              cd /workspace/scripts/
              ./simple-build-translator.sh
              cd /workspace 
              make build
              make compile-po
            " 

      - name: Prepare artifact structure
        run: |
          mkdir -p artifact_stage/build
          cp -r build/linux artifact_stage/build
          cp -r bin/ artifact_stage/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-app-image-${{ hashFiles('scripts/simple-build-translator.sh', 'patch/translations.patch' , '.github/workflows/build-app-image.yml') }}
          path: |
            artifact_stage
          if-no-files-found: error


